//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtInfo
    {
        public int ID { get; set; }
        public string Artist { get; set; }
        public string Year { get; set; }
        public string Genre { get; set; }
        public string Medium { get; set; }
        public byte[] ImageFile { get; set; }
    }
}
